### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Validation

### ISSUE THREAD

**Issue by invlpg** [mangh/llvm2019#3]
```
3/15/2021 3:19:34 PM - Microsoft VSIX Installer
3/15/2021 3:19:34 PM - -------------------------------------------
3/15/2021 3:19:34 PM - vsixinstaller.exe version:
3/15/2021 3:19:34 PM - 16.8.3038
3/15/2021 3:19:34 PM - -------------------------------------------
3/15/2021 3:19:34 PM - Command line parameters:
3/15/2021 3:19:34 PM - G:\vs\Common7\IDE\vsixinstaller.exe,/appidinstallpath:G:\vs\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.8.30907.101,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,C:\Users\_xeroxz\AppData\Local\Temp\VSIXjgtmbbke.vsix
3/15/2021 3:19:34 PM - -------------------------------------------
3/15/2021 3:19:34 PM - Microsoft VSIX Installer
3/15/2021 3:19:34 PM - -------------------------------------------
3/15/2021 3:19:34 PM - Initializing Install...
3/15/2021 3:19:35 PM - Extension Details...
3/15/2021 3:19:35 PM - 	Identifier         : llvm2019.36c7e004-3301-41f5-a2bf-06d018b89040
3/15/2021 3:19:35 PM - 	Name               : llvm2019
3/15/2021 3:19:35 PM - 	Author             : Marek Aniola
3/15/2021 3:19:35 PM - 	Version            : 1.0
3/15/2021 3:19:35 PM - 	Description        : Allows the LLVM Compiler Toolchain (installed separately) to be used from within Visual Studio 2019 (only) to build C/C++ Projects.
3/15/2021 3:19:35 PM - 	Locale             : en-US
3/15/2021 3:19:35 PM - 	MoreInfoURL        : https://github.com/mangh/llvm2019
3/15/2021 3:19:35 PM - 	InstalledByMSI     : False
3/15/2021 3:19:35 PM - 	SupportedFrameworkVersionRange : [4.5,)
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - 	SignatureState     : Unsigned
3/15/2021 3:19:35 PM - 	Supported Products : 
3/15/2021 3:19:35 PM - 		Microsoft.VisualStudio.Community
3/15/2021 3:19:35 PM - 			Version : [16.0,17.0)
3/15/2021 3:19:35 PM - 		Microsoft.VisualStudio.Pro
3/15/2021 3:19:35 PM - 			Version : [16.0,17.0)
3/15/2021 3:19:35 PM - 		Microsoft.VisualStudio.Enterprise
3/15/2021 3:19:35 PM - 			Version : [16.0,17.0)
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - 	References         : 
3/15/2021 3:19:35 PM - 	Prerequisites      : 
3/15/2021 3:19:35 PM - 		-------------------------------------------------------
3/15/2021 3:19:35 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/15/2021 3:19:35 PM - 		Name         : Visual Studio core editor
3/15/2021 3:19:35 PM - 		Version      : [16.0,17.0)
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - 		-------------------------------------------------------
3/15/2021 3:19:35 PM - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core
3/15/2021 3:19:35 PM - 		Name         : C++ core desktop features
3/15/2021 3:19:35 PM - 		Version      : [16.0,17.0)
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - 		-------------------------------------------------------
3/15/2021 3:19:35 PM - 		Identifier   : Microsoft.VisualStudio.Component.VC.CoreIde
3/15/2021 3:19:35 PM - 		Name         : C++ core features
3/15/2021 3:19:35 PM - 		Version      : [16.0,17.0)
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - Signature Details...
3/15/2021 3:19:35 PM - 	Extension is not signed.
3/15/2021 3:19:35 PM - 
3/15/2021 3:19:35 PM - System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.Threading.AsyncLazy`1..ctor(Func`1 valueFactory, JoinableTaskFactory joinableTaskFactory)
   at Microsoft.VisualStudio.ExtensionManager.InstalledExtensionListData.CreateExtensionListData(ExtensionEngineImpl engine, IEnumerable`1 enabledExtensions, Boolean safeMode, Boolean isSdkList)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl..ctor(IEngineHost engineHost, EngineMode mode, IEnumerable`1 enabledExtensions, CancellationToken disposalToken)
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by invlpg** [comment]
Not sure what the issue was but what I did was opened visual studio installer, ran the vsix installer and it worked :)

**Comment by LuigiZambetti** [comment]
Have you ever find a solution for this?
